[package]
name = "gltf2glb"
version = "0.1.0"
authors = ["Andreas Streichardt <andreas@mop.koeln>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
clap = "2.33.0"
serde_json = "1.0.48"